server:
  port: 80
  max-http-header-size: 10240

guns:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model

log:
  path: guns-logs

# 启用 Dataway 功能（默认不启用）
HASOR_DATAQL_DATAWAY: true
# 开启 ui 管理功能（注意生产环境必须要设置为 false，否则会造成严重的生产安全事故）
HASOR_DATAQL_DATAWAY_ADMIN: true

# （可选）API工作路径
HASOR_DATAQL_DATAWAY_API_URL: /api/
# （可选）ui 的工作路径，只有开启 ui 管理功能后才有效
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql